nume = str(input("Cum te numesti?\n"))
virsta = str(input("Cati ani ai?\n"))
scoala = str(input("In ce scoala inveti?\n"))
obiect = str(input("Care e obiectul preferent?\n"))
print(f'Te numesti {nume}, ai {virsta} ani, inveti in {scoala} si obiectul tau preferat este {obiect}, iti doresc mult succes in continuare')
